name: release
on:
  push:
    tags: ['v*.*.*']
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    -
      name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    -
      name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Release in krew-index
      uses: rajatjindal/krew-release-bot@v0.0.47
